#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parent
WEB = ROOT / "web"
OUT = ROOT / "web_pages.h"

PAGES = (
    ("SETUP_PAGE", "setup.html"),
    ("LIGHT_PAGE", "light.html"),
    ("SAVED_PAGE", "saved.html"),
)


def main() -> None:
    chunks = [
        "/* Generated by embed_pages.py. Edit web/*.html, then rerun this script. */\n",
        "#pragma once\n\n",
    ]
    for name, filename in PAGES:
        html = (WEB / filename).read_text(encoding="utf-8")
        if ")HTML" in html:
            raise SystemExit(f"{filename} contains )HTML, which would break the string wrapper")
        chunks.append(f'const char {name}[] PROGMEM = R"HTML({html})HTML";\n\n')
    OUT.write_text("".join(chunks), encoding="utf-8")


if __name__ == "__main__":
    main()
